## Cluster Settings
cluster.name: stac-cluster
node.name: os01
network.host: 0.0.0.0
transport.host: 0.0.0.0
discovery.type: single-node
http.port: 9202
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-methods: GET, POST, PUT, DELETE, OPTIONS
http.cors.allow-headers: Authorization, Content-Type

path:
  repo:
    - /usr/share/opensearch/snapshots

# Security
plugins.security.disabled: true
plugins.security.ssl.http.enabled: true

node.max_local_storage_nodes: 3
